---
schemaVersion: "v2"
---
cluster:
  name: grappleberry
  domain: k8s.local
distribution:
  type: okd
  version: "4.22.0-okd-scos.7"
provider:
  type: proxmox
  proxmox:
    host: 192.168.227.195
    node: pve
    storage: local-lvm
    iso_storage: local
    bridge: vmbr0
topology:
  control_plane:
    count: 3
    cpu: 4
    memory_mb: 16384 # 16 GB
    disk_gb: 100
  workers:
    count: 3
    cpu: 8
    memory_mb: 32768 # 32 GB
    disk_gb: 200
networking:
  machine_cidr: 192.168.227.0/24
  pod_cidr: 10.128.0.0/14
  service_cidr: 172.30.0.0/16
  gateway: 192.168.227.1
  dns:
    - 192.168.227.1
addons:
  flux:
    enabled: true
    settings:
      provider: flux
      branch: main
      path: kubernetes/clusters/production
