package cleanup

import (
	"context"
	"log/slog"
	"path/filepath"
)

// IgnitionCerts removes the generated TLS cert and key directory under
// projectRoot/certs/ignition. The cert is regenerated by setup if missing,
// so removal is safe between runs.
func IgnitionCerts(ctx context.Context, projectRoot string, logger *slog.Logger) error {
	certDir := filepath.Join(projectRoot, "certs", "ignition")
	return SafeRemoveWithLogger(ctx, certDir, "ignition TLS certs", logger)
}
